version: "3.2"
services:
  db:
    image: postgres
    restart: always
    ports:
      - 4444:5432
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
volumes:
  database_data:
    driver: local
  data01:
    driver: local

networks:
  elastic:
    driver: bridge
