version: "3.2"
services:
  db:
    image: postgres
    restart: always
    ports:
      - 4444:5432
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
volumes:
  database_data:
    driver: local
